name: Main

on:
  push:
    branches:
    - main
    tags:
    - v*
  pull_request:
    branches:
    - main

jobs:

  stormforge-perf:
    name: StormForge Perf
    uses: ./.github/workflows/build-push.yaml
    with:
      dir: stormforge-perf

  locust:
    name: Locust
    uses: ./.github/workflows/build-push.yaml
    with:
      dir: locust
