name: Promote

on:
  workflow_call:
    inputs:
      version:
        description: Release version to promote
        required: true
        default: ''
        type: string
      dir:
        description: Directory to promote
        required: true
        default: ''
        type: string
    secrets:
      username:
        description: Docker Hub username
        required: true
      password:
        description: Docker Hub password
        required: true

jobs:
  promote:
    name: Promote
    runs-on: ubuntu-latest
    steps:

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}

    - name: Promote
      run: |
        docker pull ghcr.io/${{ github.repository }}:${{ inputs.version }}-${{ inputs.dir }}

        docker tag ghcr.io/${{ github.repository }}:${{ inputs.version }}-${{ inputs.dir }} ${{ github.repository }}:${{ inputs.version }}-${{ inputs.dir }}
        docker tag ghcr.io/${{ github.repository }}:${{ inputs.version }}-${{ inputs.dir }} ${{ github.repository }}:latest-${{ inputs.dir }}

        docker push ${{ github.repository }}:${{ inputs.version }}-${{ inputs.dir }}
        docker push ${{ github.repository }}:latest-${{ inputs.dir }}
