name: Promote

on:
  workflow_call:
    inputs:
      version:
        description: Release version to promote
        required: true
        default: ''
        type: string
      dir:
        description: Directory to promote
        required: true
        default: ''
        type: string

jobs:
  promote:
    name: Promote ${{ inputs.dir }}
    runs-on: ubuntu-latest
    steps:

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Promote
      run: |
        docker pull ghcr.io/${{ github.repository }}:${{ inputs.version }}-${{ inputs.dir }}

        docker tag ghcr.io/${{ github.repository }}:${{ inputs.version }}-${{ inputs.dir }} ${{ github.repository }}:${{ inputs.version }}-${{ inputs.dir }}
        docker tag ghcr.io/${{ github.repository }}:${{ inputs.version }}-${{ inputs.dir }} ${{ github.repository }}:latest-${{ inputs.dir }}

        docker push ${{ github.repository }}:${{ inputs.version }}-${{ inputs.dir }}
        docker push ${{ github.repository }}:latest-${{ inputs.dir }}
