name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: StormForge Performance push release images
      run: |
        TAG=${GITHUB_REF##*/}-stormforge-perf
        docker pull ghcr.io/${{ github.repository }}:${TAG}
        docker tag ghcr.io/${{ github.repository }}:${TAG} ${{ github.repository }}:${TAG}
        docker tag ghcr.io/${{ github.repository }}:${TAG} ${{ github.repository }}:latest-stormforge-perf
        docker push ${{ github.repository }}:${TAG}
        docker push ${{ github.repository }}:latest-stormforge-perf

    - name: Locust push release images
      run: |
        TAG=${GITHUB_REF##*/}-locust
        docker pull ghcr.io/${{ github.repository }}:${TAG}
        docker tag ghcr.io/${{ github.repository }}:${TAG} ${{ github.repository }}:${TAG}
        docker tag ghcr.io/${{ github.repository }}:${TAG} ${{ github.repository }}:latest-locust
        docker push ${{ github.repository }}:${TAG}
        docker push ${{ github.repository }}:latest-locust
