name: Test JMeter

on:
  push:
    paths:
    - 'jmeter/**'
    - '.github/workflows/test-jmeter.yaml'
    - '.github/actions/*'

jobs:
  test-jmeter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
       scandir: "jmeter/docker-entrypoint.sh"
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: "latest"
        install: true
    - name: Build Image
      uses: docker/build-push-action@v3
      with:
        context: ./jmeter
        push: false
        pull: true
        load: true
        tags: sf-trial-image-test-subject
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Setup Docker Network
      run: |
        docker network create --driver bridge sf-test
    - name: Start Pushgateway
      run: |
        docker run --network sf-test --name pushgateway -d -p 9091:9091 prom/pushgateway
    - name: Start Testapp
      run: |
        docker run --network sf-test --name testapp -d -p 8080:8080 --env DISABLE_TLS=true stormforger/testapp

    - name: Run JMeter image
      working-directory: jmeter
      run: |
        docker run \
          --network sf-test \
          -v ${PWD}/test:/test \
          --env PUSHGATEWAY_URL=http://pushgateway:9091/metrics/job/sf_trial_test \
          --env TEST_CASE_FILE=/test/simple.js \
          sf-trial-image-test-subject

    - name: Test metrics from Pushgateway
      working-directory: jmeter
      run: |
        echo "Scraping metrics from Pushgateway..."
        curl --no-progress-meter http://localhost:9091/api/v1/metrics > tmp/metrics.json
        
        echo "Testing against metrics..."
        test "$(jq -r '.data[0].http_reqs_count.metrics[0].value' tmp/metrics.json)" -eq "1"
